import { X, Copy, Check, Download } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Paper } from "@/data/papers";
import { useToast } from "@/hooks/use-toast";

interface ReadmeModalProps {
  paper: Paper | null;
  isOpen: boolean;
  onClose: () => void;
}

const generateReadme = (paper: Paper): string => {
  return `# ${paper.title}

## Overview

${paper.abstract}

## Authors

${paper.authors.map((author) => `- ${author}`).join("\n")}

## Publication Details

| Field | Value |
|-------|-------|
| **Journal** | Nature |
| **Published** | ${new Date(paper.publishedDate).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })} |
| **DOI** | ${paper.doi} |
| **Citations** | ${paper.citations} |
| **Category** | ${paper.category} |

## Links

- 📄 **Paper**: [Nature Article](${paper.natureUrl})
${paper.githubUrl ? `- 💻 **Code**: [GitHub Repository](${paper.githubUrl})` : ""}
${paper.datasetUrl ? `- 📊 **Dataset**: [Access Dataset](${paper.datasetUrl})` : ""}

${
  paper.datasetUrl
    ? `## Dataset

${paper.datasetDescription}

### Access

\`\`\`bash
# Download dataset
wget ${paper.datasetUrl}
\`\`\`
`
    : ""
}

${
  paper.githubUrl
    ? `## Installation

\`\`\`bash
# Clone the repository
git clone ${paper.githubUrl}
cd ${paper.githubUrl.split("/").pop()}

# Install dependencies
pip install -r requirements.txt
\`\`\`
`
    : ""
}

## Citation

\`\`\`bibtex
@article{${paper.authors[0]?.split(" ").pop()?.toLowerCase() || "author"}${new Date(paper.publishedDate).getFullYear()},
  title={${paper.title}},
  author={${paper.authors.join(" and ")}},
  journal={Nature},
  year={${new Date(paper.publishedDate).getFullYear()}},
  doi={${paper.doi}}
}
\`\`\`

## Tags

${paper.tags.map((tag) => `\`${tag}\``).join(" ")}

---

*Generated by MatSci Papers Hub*
`;
};

const ReadmeModal = ({ paper, isOpen, onClose }: ReadmeModalProps) => {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  if (!paper || !isOpen) return null;

  const readme = generateReadme(paper);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(readme);
    setCopied(true);
    toast({
      title: "Copied to clipboard",
      description: "README content has been copied.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([readme], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `README-${paper.id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded",
      description: "README.md file has been downloaded.",
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-foreground/20 backdrop-blur-sm animate-fade-in"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="relative z-10 w-full max-w-3xl max-h-[85vh] rounded-xl bg-card border border-border shadow-2xl overflow-hidden animate-scale-in">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border px-6 py-4">
          <div>
            <h2 className="text-lg font-semibold text-foreground">Generated README</h2>
            <p className="text-sm text-muted-foreground">{paper.title}</p>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              {copied ? (
                <Check className="h-4 w-4 text-primary" />
              ) : (
                <Copy className="h-4 w-4" />
              )}
              {copied ? "Copied" : "Copy"}
            </Button>
            <Button variant="outline" size="sm" onClick={handleDownload}>
              <Download className="h-4 w-4" />
              Download
            </Button>
            <button
              onClick={onClose}
              className="ml-2 rounded-lg p-2 hover:bg-secondary transition-colors"
            >
              <X className="h-5 w-5 text-muted-foreground" />
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="overflow-auto max-h-[calc(85vh-80px)] p-6">
          <pre className="whitespace-pre-wrap font-mono text-sm text-foreground bg-secondary/50 rounded-lg p-4 overflow-x-auto">
            {readme}
          </pre>
        </div>
      </div>
    </div>
  );
};

export default ReadmeModal;
